# @name createMessage
POST {{ $dotenv baseUrl }}
Content-Type: application/json

{
  "route": "messages",
  "endPoint": "createMessage",
  "publicKey": "{{$dotenv publicKey}}",
  "token": "{{$dotenv adminToken}}",
  "tokenRow": "{{$dotenv adminTokenRow}}",
  "message": "New Message",
  "isPublic": "FALSE"
}

### GET Answer
@answerURL = {{ createMessage.response.headers.Location }}
GET {{ answerURL }}
