# @name deleteMessage
POST {{ $dotenv baseUrl }}
Content-Type: application/json

{
  "route": "messages",
  "endPoint": "deleteMessage",
  "publicKey": "{{$dotenv publicKey}}",
  "token": "{{$dotenv token}}",
  "tokenRow": "{{$dotenv tokenRow}}",
  "messageId": 0
}

### GET Answer
@answerURL = {{ deleteMessage.response.headers.Location }}
GET {{ answerURL }}
