# @name logoff
POST {{ $dotenv baseUrl }}
Content-Type: application/json

{
  "route": "logoff",
  "publicKey": "{{$dotenv publicKey}}",
  "token": "{{$dotenv token}}",
  "tokenRow": "{{$dotenv tokenRow}}"
}

### GET Answer
@answerURL = {{ logoff.response.headers.Location }}
GET {{ answerURL }}